"""Run this script once to produce PIDeepONet_massDiffusion_transient.ipynb"""
import json, uuid

def uid():
    return str(uuid.uuid4())[:8]

def code(src):
    return {"cell_type": "code", "execution_count": None,
            "id": uid(), "metadata": {}, "outputs": [],
            "source": src if isinstance(src, list) else [src]}

def md(src):
    return {"cell_type": "markdown", "id": uid(), "metadata": {},
            "source": src if isinstance(src, list) else [src]}

# ─────────────────────────────────────────────────────────────────────────────
cells = []

# ── Cell 1: problem description ───────────────────────────────────────────────
cells.append(md([
    "## Transient Mass Diffusion\n",
    "\n",
    "We consider transient mass diffusion in a 2-D heterogeneous material:\n",
    "$$\n",
    "\\frac{\\partial C}{\\partial t} = \\nabla\\cdot\\bigl(D(x,y)\\,\\nabla C\\bigr),\n",
    "\\quad (x,y)\\in[0,1]^2,\\; t\\in[0,T]\n",
    "$$\n",
    "\n",
    "**Boundary conditions**\n",
    "- Left ($x=0$): $C=1$ &nbsp; (Dirichlet)\n",
    "- Right ($x=1$): $C=0$ &nbsp; (Dirichlet)\n",
    "- Top/bottom: zero normal flux (Neumann)\n",
    "\n",
    "**Initial condition**: $C(x,y,0)=1-x$\n",
    "&nbsp;&nbsp;*(linear profile — consistent with the BCs, avoids corner singularities)*\n",
    "\n",
    "**Diffusivity**: $D(x,y)=\\exp(\\alpha x+\\beta y)$, $\\;\\alpha,\\beta\\sim\\mathrm{Uniform}(-1,1)$\n",
    "\n",
    "### Neural operator learning problem\n",
    "$$\\mathcal{G}: D(x,y) \\;\\longrightarrow\\; C(x,y,t)$$\n",
    "\n",
    "The trunk net takes $(x,y,t)$ as input.  \n",
    "The time-gated mollifier encodes **all** constraints by construction:\n",
    "$$C = u_\\theta\\cdot x(1-x)\\sin(\\pi y)\\cdot\\underbrace{(1-e^{-t/\\tau})}_{\\text{time gate}} + (1-x)$$\n",
    "- $t=0$: time gate $=0 \\Rightarrow C=1-x$ &nbsp;✓ (IC exactly)\n",
    "- $x=0$: $C=1$ &nbsp;✓ &nbsp; $x=1$: $C=0$ &nbsp;✓\n",
    "- $y=0,1$: $C=1-x$ (Neumann-consistent) &nbsp;✓\n",
]))

# ── Cell 2: setup + data loading ──────────────────────────────────────────────
cells.append(code([
    "import sys\n",
    "sys.path.append('../..')\n",
    "import numpy as np\n",
    "import h5py\n",
    "import torch\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def setup_seed(seed):\n",
    "    torch.manual_seed(seed)\n",
    "    torch.cuda.manual_seed_all(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.backends.cudnn.deterministic = True\n",
    "\n",
    "random_seed = 1234\n",
    "setup_seed(random_seed)\n",
    "\n",
    "if torch.cuda.is_available():\n",
    "    device = 'cuda:0'\n",
    "elif torch.backends.mps.is_available():\n",
    "    device = 'mps'\n",
    "else:\n",
    "    device = 'cpu'\n",
    "\n",
    "dtype = torch.float32\n",
    "problem_name = 'massDiffusion_2d'\n",
    "tag          = 'diff_transient'\n",
    "\n",
    "# ── physics / discretisation parameters ──────────────────────────────────────\n",
    "T   = 2.0    # total simulation time\n",
    "n_t = 11     # saved time snapshots: t = 0, 0.2, 0.4, ..., 2.0\n",
    "tau = 0.5    # mollifier time constant\n",
    "res = 29     # spatial grid resolution\n",
    "\n",
    "# ── load dataset (run Problems/massDiffusion_2d/gen_data_transient.py first) ─\n",
    "data_train = h5py.File('../../Problems/massDiffusion_2d/diff_transient_train.mat', 'r')\n",
    "data_test  = h5py.File('../../Problems/massDiffusion_2d/diff_transient_test_in.mat',  'r')\n",
    "print('train keys:', list(data_train.keys()))\n",
    "\n",
    "from Utils.utils import *\n",
    "n_train, n_test = 1000, 200\n",
    "\n",
    "def get_data(data, ndata, dtype, n0=0):\n",
    "    # coeff:   (nx, ny, n_samples)       → .T → (n_samples, ny, nx)\n",
    "    a = np2tensor(np.array(data['coeff'][..., n0:n0+ndata]).T, dtype)\n",
    "    # sol_fdm: (nx, ny, n_t, n_samples)  → .T → (n_samples, n_t, ny, nx)\n",
    "    u = np2tensor(np.array(data['sol_fdm'][..., n0:n0+ndata]).T, dtype)\n",
    "\n",
    "    t_arr = np.array(data['t_arr'])                   # (n_t,)\n",
    "    X, Y  = np.array(data['X']).T, np.array(data['Y']).T  # (ny, nx)\n",
    "    ny_g, nx_g = X.shape\n",
    "\n",
    "    # spatial mesh: (nx*ny, 2)\n",
    "    spatial_mesh = np2tensor(np.vstack([X.ravel(), Y.ravel()]).T, dtype)\n",
    "\n",
    "    # space-time mesh: for each t snapshot, all spatial points → (n_t*nx*ny, 3)\n",
    "    x_list = []\n",
    "    for t_k in t_arr:\n",
    "        t_col = torch.full((nx_g * ny_g, 1), float(t_k), dtype=dtype)\n",
    "        x_list.append(torch.cat([spatial_mesh, t_col], dim=-1))\n",
    "    x_st = torch.cat(x_list, dim=0)            # (n_t*nx*ny, 3)\n",
    "\n",
    "    x = x_st.unsqueeze(0).repeat(ndata, 1, 1)  # (ndata, n_t*nx*ny, 3)\n",
    "    a = a.reshape(ndata, -1, 1)                 # (ndata, nx*ny, 1)\n",
    "    u = u.reshape(ndata, -1, 1)                 # (ndata, n_t*nx*ny, 1)\n",
    "\n",
    "    return a, u, x, spatial_mesh, t_arr\n",
    "\n",
    "a_train, u_train, x_train, grid_train, t_arr = get_data(data_train, n_train, dtype)\n",
    "a_test,  u_test,  x_test,  grid_test,  _     = get_data(data_test,  n_test,  dtype)\n",
    "\n",
    "print('a_train:', a_train.shape)   # (1000, 841, 1)\n",
    "print('u_train:', u_train.shape)   # (1000, 9251, 1)\n",
    "print('x_train:', x_train.shape)   # (1000, 9251, 3)\n",
    "print('t_arr:',   t_arr)\n",
    "\n",
    "# spatial-only mesh for PDE collocation (no time component)\n",
    "from Utils.GenPoints import Point2D\n",
    "pointGen = Point2D(x_lb=[0., 0.], x_ub=[1., 1.], dataType=dtype, random_seed=random_seed)\n",
    "N_mesh  = 29\n",
    "x_mesh  = pointGen.inner_point(N_mesh, method='mesh')   # (841, 2)\n",
    "print('x_mesh:', x_mesh.shape)\n",
]))

# ── Cell 3: method description ────────────────────────────────────────────────
cells.append(md([
    "## PIDeepONet — transient formulation\n",
    "\n",
    "### PDE loss\n",
    "At each training step, $N_t=5$ time points are sampled uniformly in $(0,T]$.\n",
    "For each $t_k$:\n",
    "1. Evaluate $C$ on the $29\\times29$ spatial mesh via the model + mollifier.\n",
    "2. Compute $\\partial C/\\partial t$ by **automatic differentiation** through the trunk net.\n",
    "3. Compute $\\nabla\\cdot(D\\nabla C)$ by two passes of the same FDM used in the steady-state case.\n",
    "4. Accumulate residual $\\|\\partial C/\\partial t - \\nabla\\cdot(D\\nabla C)\\|^2$.\n",
    "\n",
    "No IC loss is needed — the time gate in the mollifier satisfies $C(x,y,0)=1-x$ exactly.\n",
]))

# ── Cell 4: LossClass + model ─────────────────────────────────────────────────
cells.append(code([
    "from Utils.Grad import *\n",
    "import torch.nn as nn\n",
    "from torch.autograd import Variable\n",
    "\n",
    "N_t_pde = 5   # time points sampled per batch for PDE residual\n",
    "\n",
    "# ── nearest-neighbour lookup of D on the spatial mesh ────────────────────────\n",
    "class fun_a(object):\n",
    "    def __init__(self, res):\n",
    "        self.res   = res\n",
    "        self.delta = 1. / (res - 1)\n",
    "\n",
    "    def __call__(self, x, a):\n",
    "        # x: (N, 2) spatial-only points\n",
    "        a = a.squeeze(-1)\n",
    "        x_loc = torch.floor(x[..., 0] / self.delta + 0.5).int()\n",
    "        y_loc = torch.floor(x[..., 1] / self.delta + 0.5).int()\n",
    "        loc   = y_loc * self.res + x_loc\n",
    "        img   = a[torch.arange(a.size(0)).unsqueeze(1), loc]\n",
    "        return img.unsqueeze(-1)\n",
    "\n",
    "\n",
    "# ── time-gated mollifier ──────────────────────────────────────────────────────\n",
    "class mollifier(object):\n",
    "    # C = u_nn * x*(1-x)*sin(pi*y) * (1 - exp(-t/tau))  +  (1-x)\n",
    "    # Satisfies IC (t=0), Dirichlet BCs (x=0,1), and Neumann-consistency (y=0,1)\n",
    "    def __call__(self, u, x):\n",
    "        xx = x[..., 0:1]\n",
    "        yy = x[..., 1:2]\n",
    "        tt = x[..., 2:3]\n",
    "        time_gate = 1.0 - torch.exp(-tt / tau)\n",
    "        return u * xx * (1 - xx) * torch.sin(np.pi * yy) * time_gate + (1 - xx)\n",
    "\n",
    "\n",
    "# ── LossClass ─────────────────────────────────────────────────────────────────\n",
    "class LossClass(object):\n",
    "\n",
    "    def __init__(self, solver):\n",
    "        self.solver    = solver\n",
    "        self.dtype     = solver.dtype\n",
    "        self.device    = solver.device\n",
    "        self.fun_a     = fun_a(res=res)\n",
    "        self.model_u   = solver.model_dict['u']\n",
    "        self.mollifier = mollifier()\n",
    "        self.deltax    = 1. / (N_mesh - 1)\n",
    "        self.deltay    = 1. / (N_mesh - 1)\n",
    "\n",
    "    def Loss_pde(self, a_batch, w_pde):\n",
    "        '''PDE loss: dC/dt - div(D grad C) = 0'''\n",
    "        n_batch = a_batch.shape[0]\n",
    "        if w_pde == 0.:\n",
    "            return torch.tensor(0.)\n",
    "\n",
    "        # D values at spatial mesh (time-independent)\n",
    "        a_sp   = self.fun_a(x_mesh, a_batch)                       # (batch, N², 1)\n",
    "        a_grid = a_sp.reshape(n_batch, N_mesh, N_mesh, 1)\n",
    "\n",
    "        # sample time points uniformly in (0, T]\n",
    "        t_pts = torch.linspace(T / N_t_pde, T, N_t_pde, dtype=self.dtype)\n",
    "\n",
    "        loss_total = torch.tensor(0., device=self.device)\n",
    "\n",
    "        for t_k in t_pts:\n",
    "            # build (x, y, t_k) input with requires_grad so autograd flows through t\n",
    "            t_col = torch.full((N_mesh * N_mesh, 1), t_k.item(), dtype=self.dtype)\n",
    "            x_st  = torch.cat([x_mesh, t_col], dim=-1)             # (N², 3)\n",
    "            x_st  = Variable(\n",
    "                x_st.unsqueeze(0).repeat(n_batch, 1, 1).to(self.device),\n",
    "                requires_grad=True)\n",
    "\n",
    "            u = self.model_u(x_st, a_batch)\n",
    "            u = self.mollifier(u, x_st)                            # (batch, N², 1)\n",
    "\n",
    "            # dC/dt via autograd w.r.t. x_st (last column = t)\n",
    "            grads  = torch.autograd.grad(u.sum(), x_st, create_graph=True)[0]\n",
    "            du_dt  = grads[..., 2:3]                               # (batch, N², 1)\n",
    "\n",
    "            # spatial divergence via FDM (two passes, each trims 1 layer/side)\n",
    "            u_grid = u.reshape(n_batch, N_mesh, N_mesh, 1)\n",
    "            dudx, dudy = FDM_2d(u_grid, self.deltax, self.deltay)  # → (batch, N-2, N-2, 1)\n",
    "            adux = a_grid[:, 1:-1, 1:-1, :] * dudx\n",
    "            aduy = a_grid[:, 1:-1, 1:-1, :] * dudy\n",
    "            dauxdx, _      = FDM_2d(adux, self.deltax, self.deltay)  # → (batch, N-4, N-4, 1)\n",
    "            _,      dauydy = FDM_2d(aduy, self.deltax, self.deltay)\n",
    "\n",
    "            # trim du_dt to the same (N-4)² interior after two FDM passes\n",
    "            du_dt_int = du_dt.reshape(n_batch, N_mesh, N_mesh, 1)[:, 2:-2, 2:-2, :]\n",
    "\n",
    "            residual = (du_dt_int - (dauxdx + dauydy)).reshape(n_batch, -1)\n",
    "            loss_total += self.solver.getLoss(residual, torch.zeros_like(residual))\n",
    "\n",
    "        return loss_total / N_t_pde\n",
    "\n",
    "    def Loss_data(self, x, a, u, w_data):\n",
    "        return torch.tensor(0.)\n",
    "\n",
    "    def Error(self, x, a, u):\n",
    "        u_pred = self.model_u(x, a)\n",
    "        u_pred = self.mollifier(u_pred, x)\n",
    "        return self.solver.getError(u_pred, u)\n",
    "\n",
    "\n",
    "# ── model architecture ────────────────────────────────────────────────────────\n",
    "from Solvers.PIDeepONet import PIDeepONet\n",
    "from Networks.CNNet import CNNet2d\n",
    "\n",
    "solver  = PIDeepONet.Solver(device=device, dtype=dtype)\n",
    "netType = 'DeepONetBatch'\n",
    "\n",
    "class BranchNet(nn.Module):\n",
    "    def __init__(self, conv_arch, fc_arch, nx_size, ny_size, dtype=None):\n",
    "        super().__init__()\n",
    "        self.nx_size, self.ny_size = nx_size, ny_size\n",
    "        self.conv = CNNet2d(conv_arch=conv_arch, fc_arch=fc_arch,\n",
    "                            activation_conv='SiLU', activation_fc='SiLU',\n",
    "                            kernel_size=(3, 3), stride=2, dtype=dtype)\n",
    "    def forward(self, x):\n",
    "        x = x.reshape(-1, self.ny_size, self.nx_size).unsqueeze(1)\n",
    "        return self.conv(x)\n",
    "\n",
    "conv_arch = [1, 64, 64, 64]\n",
    "fc_arch   = [64 * 2 * 2, 128, 128, 128]\n",
    "branchNet = BranchNet(conv_arch, fc_arch, nx_size=res, ny_size=res, dtype=dtype)\n",
    "\n",
    "# trunk net: 3 inputs (x, y, t) instead of 2\n",
    "layers_branch, activation_branch = [branchNet, fc_arch[-1]], 'SiLU'\n",
    "layers_trunk,  activation_trunk  = [3, 128, 128, 128, 128], 'ReLU'\n",
    "\n",
    "model_u = solver.getModel(layers_branch, layers_trunk, activation_branch, activation_trunk,\n",
    "                           multi_ouput_strategy=None, num_output=1, netType=netType)\n",
    "\n",
    "total = sum(p.numel() for p in model_u.parameters() if p.requires_grad)\n",
    "print(f'{total:,} trainable parameters.')\n",
]))

# ── Cell 5: training ──────────────────────────────────────────────────────────
cells.append(md(["### Train the model\n"]))

cells.append(code([
    "model_dict = {'u': model_u}\n",
    "solver.train_setup(model_dict, lr=1e-3, optimizer='Adam',\n",
    "                   scheduler_type='StepLR', gamma=0.6, step_size=200)\n",
    "solver.train(LossClass, a_train, u_train, x_train,\n",
    "             a_test,  u_test,  x_test,\n",
    "             w_data=0., w_pde=1., batch_size=50, epochs=1000, epoch_show=50,\n",
    "             **{'save_path': f'saved_models/PI{netType}_{tag}/'})\n",
]))

# ── Cell 6: prediction ────────────────────────────────────────────────────────
cells.append(md(["### Load model and visualise predictions\n"]))

cells.append(code([
    "from Solvers.PIDeepONet import PIDeepONet\n",
    "from torch.autograd import Variable\n",
    "import scipy.io\n",
    "from scipy.interpolate import griddata\n",
    "from Utils.PlotFigure import Plot\n",
    "\n",
    "solver2 = PIDeepONet.Solver(device=device, dtype=dtype)\n",
    "model_trained = solver2.loadModel(\n",
    "    path=f'saved_models/PI{netType}_{tag}/',\n",
    "    name='model_pideeponet_besterror')\n",
    "\n",
    "with torch.no_grad():\n",
    "    x_var = x_test.to(device)\n",
    "    a_var = a_test.to(device)\n",
    "    u_pred = model_trained['u'](x_var, a_var)\n",
    "    u_pred = mollifier()(u_pred, x_var).cpu()\n",
    "\n",
    "print('Test L2 error (avg):', solver2.getError(u_pred, u_test).item())\n",
    "\n",
    "# ── snapshots at 6 time points for sample 0 ──────────────────────────────────\n",
    "inx       = 0\n",
    "grid_np   = grid_test.numpy()                      # (841, 2)\n",
    "mesh_plot = np.meshgrid(np.linspace(0,1,100), np.linspace(0,1,100))\n",
    "xp, yp    = mesh_plot[0], mesh_plot[1]\n",
    "\n",
    "u_pred_st = u_pred[inx].reshape(n_t, res*res)      # (n_t, 841)\n",
    "u_true_st = u_test[inx].reshape(n_t, res*res)\n",
    "\n",
    "t_show_idx = [0, 2, 4, 6, 8, 10]                   # t=0,0.4,0.8,1.2,1.6,2.0\n",
    "t_show_val = t_arr[t_show_idx]\n",
    "\n",
    "import matplotlib\n",
    "import scienceplots\n",
    "fig, axes = plt.subplots(3, len(t_show_idx), figsize=(4*len(t_show_idx), 10))\n",
    "\n",
    "for col, (tidx, tval) in enumerate(zip(t_show_idx, t_show_val)):\n",
    "    tr  = u_true_st[tidx].numpy()\n",
    "    pr  = u_pred_st[tidx].numpy()\n",
    "    er  = np.abs(tr - pr)\n",
    "    zt  = griddata((grid_np[:,0], grid_np[:,1]), tr, (xp,yp), method='cubic')\n",
    "    zp  = griddata((grid_np[:,0], grid_np[:,1]), pr, (xp,yp), method='cubic')\n",
    "    ze  = griddata((grid_np[:,0], grid_np[:,1]), er, (xp,yp), method='cubic')\n",
    "    with plt.style.context(['science','no-latex']):\n",
    "        for ax, z, lbl in zip(axes[:,col], [zt,zp,ze],\n",
    "                               [f'$C_{{true}}$  t={tval:.1f}',\n",
    "                                f'$C_{{pred}}$  t={tval:.1f}',\n",
    "                                f'$|error|$  t={tval:.1f}']):\n",
    "            cf = ax.contourf(xp, yp, z, levels=14, cmap='jet')\n",
    "            fig.colorbar(cf, ax=ax, shrink=0.8)\n",
    "            ax.set_title(lbl, fontsize=11)\n",
    "            ax.set_xlabel('x'); ax.set_ylabel('y')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# ── loss and error curves ─────────────────────────────────────────────────────\n",
    "loss_saved = solver2.loadLoss(\n",
    "    path=f'saved_models/PI{netType}_{tag}/', name='loss_pideeponet')\n",
    "Plot.show_loss([loss_saved['loss_pde']], ['PDE loss'])\n",
    "Plot.show_error([loss_saved['time']], [loss_saved['error']], ['L2 test error'])\n",
]))

# ─────────────────────────────────────────────────────────────────────────────
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

out = 'PIDeepONet_massDiffusion_transient.ipynb'
with open(out, 'w') as f:
    json.dump(nb, f, indent=1)
print(f'Written: {out}')
